http://127.0.0.1:5000/ /register /login /groups /groups/<int:pid>/owner  #TODO MOVER A USER HANDLER Y DAO
/groups/<int:gid>/members

/messages ##TODO NOT FOUND

/messages/by/<int:pid>

/groups/<int:gid>/messages

/groups/<int:gid>/messages/by/<int:pid>

/<int:pid>/contacts

/<int:pid>/contacts/<string:name> #TODO IMPLEMENT

/messages/<int:mid>/number-of-likes

/messages/<int:mid>/who-likes #TypeError: getWhoLikedMessage() missing 1 required positional argument: 'mid'

/messages/<int:mid>/number-of-dislikes

/messages/<int:mid>/who-likes #TypeError: getWhoLikedMessage() missing 1 required positional argument: 'mid'